package com.buildledger.notification.enums;
public enum NotificationType
{   //IAM
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_DELETED,

    //vendor
    VENDOR_REGISTERED,
    VENDOR_ACTIVATED,
    VENDOR_SUSPENDED,
    VENDOR_DELETED,
    VENDOR_PROFILE_UPDATED,
    VENDOR_DOCUMENT_PENDING,
    VENDOR_DOCUMENT_UPLOADED,
    VENDOR_DOCUMENT_REPLACED,
    VENDOR_DOCUMENT_APPROVED,
    VENDOR_DOCUMENT_REJECTED,

    //contract
    CONTRACT_ACTIVATED,

    //invoice
    INVOICE_APPROVED,
    INVOICE_REJECTED,
    INVOICE_SUBMITTED,
    INVOICE_PAID,
    INVOICE_DELETED,

    //payment
    PAYMENT_COMPLETED,
    PAYMENT_INITIATED,
    PAYMENT_PROCESSING,
    PAYMENT_FAILED,

    //delivery
    DELIVERY_CREATED,
    DELIVERY_UPDATED,
    DELIVERY_MARKED_DELIVERED,
    DELIVERY_DELETED,
    DELIVERY_ACCEPTED,
    DELIVERY_REJECTED,

    //audit
    AUDIT_SCHEDULED,

    //compliance
    COMPLIANCE_RECORD_CREATED,
    COMPLIANCE_RECORD_UPDATED,
    COMPLIANCE_REVIEW_STARTED,
    COMPLIANCE_PASSED,
    COMPLIANCE_WAIVED,
    COMPLIANCE_REINITIATED,
    COMPLIANCE_RECORD_DELETED,

    //project
    PROJECT_CREATED,       // ← ADD THIS
    PROJECT_STATUS_CHANGED,
    PROJECT_UPDATED,   // ← ADD
//    COMPLIANCE_REVIEW_DUE,
//    COMPLIANCE_OVERDUE,
    GENERAL
}

