package com.buildledger.notification.enums;
public enum NotificationType
{
    VENDOR_REGISTERED,
//    VENDOR_APPROVED,
//    VENDOR_REJECTED,
    VENDOR_ACTIVATED,
    VENDOR_SUSPENDED,
    VENDOR_DELETED,
    VENDOR_PROFILE_UPDATED,
    VENDOR_DOCUMENT_PENDING,
    VENDOR_DOCUMENT_UPLOADED,
    VENDOR_DOCUMENT_REPLACED,
    VENDOR_DOCUMENT_APPROVED,
    VENDOR_DOCUMENT_REJECTED,
    CONTRACT_ACTIVATED,
    INVOICE_APPROVED,
    INVOICE_REJECTED,
    PAYMENT_COMPLETED,
    DELIVERY_ACCEPTED,
    DELIVERY_REJECTED,
    AUDIT_SCHEDULED,
    COMPLIANCE_CHECK_PASSED,
    COMPLIANCE_CHECK_FAILED,
    COMPLIANCE_STATUS_CHANGED,
    PROJECT_CREATED,       // ← ADD THIS
    PROJECT_STATUS_CHANGED,
//    COMPLIANCE_REVIEW_DUE,
//    COMPLIANCE_OVERDUE,
    GENERAL
}

