package com.buildledger.notification.enums;
 
public enum NotificationType
{   //IAM
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_DELETED,

    SERVICE_CREATED,
    SERVICE_UPDATED,
    SERVICE_STARTED,
    SERVICE_COMPLETED,
    SERVICE_VERIFIED,
    SERVICE_DELETED,

 
    VENDOR_REGISTERED,
    VENDOR_ACTIVATED,
    VENDOR_SUSPENDED,
    VENDOR_DELETED,
    VENDOR_PROFILE_UPDATED,
    VENDOR_DOCUMENT_PENDING,
    VENDOR_DOCUMENT_UPLOADED,
    VENDOR_DOCUMENT_REPLACED,
    VENDOR_DOCUMENT_APPROVED,
    VENDOR_DOCUMENT_REJECTED,

 
    CONTRACT_CREATED,
    CONTRACT_UPDATED,
    CONTRACT_TERM_ADDED,
    CONTRACT_TERM_EDITED,
    CONTRACT_TERM_DELETED,
    CONTRACT_ACTIVATED,
    CONTRACT_COMPLETED,
    CONTRACT_TERMINATED,
    CONTRACT_EXPIRED,
    CONTRACT_DELETED,
 
    INVOICE_APPROVED,
    INVOICE_REJECTED,
    INVOICE_SUBMITTED,
    INVOICE_PAID,
    INVOICE_DELETED,
  
    SCHEDULER_INVOICE_DUE_REMINDER,
    SCHEDULER_INVOICE_OVERDUE_ALERT,

 
    PAYMENT_COMPLETED,
    PAYMENT_INITIATED,
    PAYMENT_PROCESSING,
    PAYMENT_FAILED,

    DELIVERY_CREATED,
    DELIVERY_UPDATED,
    DELIVERY_MARKED_DELIVERED,
    DELIVERY_DELETED,
    DELIVERY_ACCEPTED,
    DELIVERY_REJECTED,
    DELIVERY_DELAYED,                    // ← ADDED

    // Scheduler
    SCHEDULER_DELIVERY_OVERDUE_ALERT,
    SCHEDULER_SERVICE_OVERDUE_ALERT,

    // Audit
    AUDIT_SCHEDULED,

    // Compliance
    COMPLIANCE_RECORD_CREATED,
    COMPLIANCE_RECORD_UPDATED,
    COMPLIANCE_REVIEW_STARTED,
    COMPLIANCE_CHECK_PASSED,             // ← ADDED
    COMPLIANCE_CHECK_FAILED,             // ← ADDED
    COMPLIANCE_STATUS_CHANGED,           // ← ADDED
    COMPLIANCE_FAILED,                   // ← ADDED
 
    COMPLIANCE_PASSED,
    COMPLIANCE_WAIVED,
    COMPLIANCE_REINITIATED,
    COMPLIANCE_RECORD_DELETED,
    COMPLIANCE_REVIEW_DUE,               // ← UNCOMMENTED
    COMPLIANCE_OVERDUE,                  // ← UNCOMMENTED

 
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_ACTIVATED,
    PROJECT_PUT_ON_HOLD,
    PROJECT_RESUMED,
    PROJECT_COMPLETED,
    PROJECT_CANCELLED,
    PROJECT_DELETED,
 
    PROJECT_MANAGER_REASSIGNED,  // ← ADD
//    COMPLIANCE_REVIEW_DUE,
//    COMPLIANCE_OVERDUE,
    GENERAL
}
